### ISSUE TITLE
install/ folder not found in output on Ubuntu 20.04

### ISSUE THREAD

**Issue by drewskoots** [awslabs/ros2-migration-tools#11]
Hello,

I've setup the ROS2 migration tool as described in the readme, however upon trying to run it I always receive this error:

```
Migration started...

Converting cmake files...COMPLETE

Converting package.xml files...Traceback (most recent call last):
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 786, in _get_writer
    write = file_or_filename.write
AttributeError: 'str' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ros_upgrader.py", line 495, in <module>
    main()
  File "ros_upgrader.py", line 489, in main
    RosUpgrader.start_upgrade()
  File "ros_upgrader.py", line 428, in start_upgrade
    RosUpgrader.convert_all_package_xml()
  File "ros_upgrader.py", line 195, in convert_all_package_xml
    tree.write(RosUpgrader.get_output_filepath(file_path), encoding="utf-8", xml_declaration=True)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 756, in write
    with _get_writer(file_or_filename, enc_lower) as write:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 792, in _get_writer
    file = open(file_or_filename, "w", encoding=encoding,
FileNotFoundError: [Errno 2] No such file or directory: '/home/andy/Documents/AWS_ROS_WS/ros2-migration-tools/output/2020-07-01_15_48_46/iiwa_ros/install/iiwa_ros/share/iiwa_ros/package.xml'
```

Running `ls` in the output folder iiwa_ros shows that it contains only CMakeLists.txt and package.xml. The install folder is not created/copied there. Could anyone give any insight into why this might be happening? I am trying to use this tool on Ubunutu 20.04 with python 3.8.2, rather than the versions that this program was originally developed for, but I personally don't think that would cause such an error.

**Comment by FL1GG** [comment]
did you ever find a solution for this @drewskoots?

**Comment by drewskoots** [comment]
This was a while back, so I'm not 100% certain, but I did manage to get it working. I think I messed around with a bunch of different approaches but finally just installed python 3.6 and ran it just fine with that. I hope that helps!
