### ISSUE TITLE
Migration of cv_camera-0.4.0

### ISSUE THREAD

**Issue by b4795** [awslabs/ros2-migration-tools#6]
Hello,

When I try to migrate cv_camera-0.4.0 (https://github.com/OTL/cv_camera/releases/tag/0.4.0) I get the following:

```
Migration started...

Converting cmake files...COMPLETE

Converting package.xml files...Traceback (most recent call last):
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 789, in _get_writer
    write = file_or_filename.write
AttributeError: 'str' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ros_upgrader.py", line 493, in <module>
    main()
  File "ros_upgrader.py", line 487, in main
    RosUpgrader.start_upgrade()
  File "ros_upgrader.py", line 426, in start_upgrade
    RosUpgrader.convert_all_package_xml()
  File "ros_upgrader.py", line 193, in convert_all_package_xml
    tree.write(RosUpgrader.get_output_filepath(file_path), encoding="utf-8", xml_declaration=True)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 759, in write
    with _get_writer(file_or_filename, enc_lower) as write:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 796, in _get_writer
    errors="xmlcharrefreplace")
FileNotFoundError: [Errno 2] No such file or directory: '/home/normal/src/ros2-migration-tools/output/2019-12-09_17_24_46/cv_camera-0.4.0/install/cv_camera/share/cv_camera/package.xml'
```
Are you able to reproduce this issue?
Could you provide a solution?

Thank you very much in advance.

Best regards.
Adriano Carvalho

**Comment by raghaprasad** [comment]
Hi @b4795 , we have tested these operations only on a docker container (ones provided by OSRF). Can you elaborate on what your build environment looks like?

**Comment by b4795** [comment]
I am using Ubuntu 18.04.
